### PR TITLE
hack for enketo to preserve prefilled timezone

### PR DESCRIPTION
**Pull request by sebastianbarry**

### CODE REVIEW

**Comment by sebastianbarry** [comment]
@JGreenlee this branch honestly seems like the fix, was there anything you think it needs before merging it into `places-survey`?

I even read the code and the code makes sense, i dont see any reviews I would make

**Comment by JGreenlee** [comment]
@sebastianbarry if you've tested it and can verify that it works, go ahead and merge and we'll go from there

**Comment by sebastianbarry** [comment]
I was able to find one issue as far as the timezone matching:

# Issue #1: Timezone switching is incorrect if we change the survey-preset time manually

How it works:
Keep in mind that for this trip, `start_time = 5:53 PM -10:00 (Pacific/Honolulu)` and `end_time = 6:09 PM -10:00 (Pacific/Honolulu)`
Screen Shot 2023-01-27 at 4 10 46 PM

These trip start/end times then get autofilled into the survey:

Screen Shot 2023-01-27 at 4 11 34 PM

If we save a tripAddition with the pre-filled times (5:53 PM and 6:09 PM) WITHOUT changing these numbers in the survey, then everything is as intended:

Screen Shot 2023-01-27 at 4 12 44 PM

However, the issue comes up if we change the values of the pre-filled times in the survey manually (in this case, to 5:55 PM and 6:00 PM):

Screen Shot 2023-01-27 at 4 13 49 PM

Screen Shot 2023-01-27 at 4 16 22 PM

Screen Shot 2023-01-27 at 4 18 09 PM


### Speculation:

I think this has to do with the `timezone` variable that is being used. I think it may be defaulting to `"-07:00"` which is the timezone for mountain time, not `"-10:00"` which is the timezone for Pacific/Honolulu. This would make sense why the time is being changed to be -3 hours what we would expect it to be.

# Issue #2: Additions affected by Issue #1 do not stick to the trip/ get input matched to the trip

Now, if we do either of the following...

* Press the refresh button
* End trip + sync and run the pipeline, and then refresh

Any of the trips that didn't follow the prefilled values for BOTH the start and the end, now do not show up in the trip any longer:

Simulator Screen Shot - iPhone 11 - 2023-01-27 at 16 23 04

**Comment by shankari** [comment]
@sebastianbarry glad you were able to reproduce the problem. were you able to add breakpoints to the code and see what the root cause is?

**Comment by JGreenlee** [comment]
I am not able to reproduce this issue.

@sebastianbarry Does the issue persist after closing and reopening the app? (ie swipe up and dismiss from recents)

I am wondering if you had previously loaded trips in GMT-7 (such as pacific daylight time) and the `tz` variable is persisting between different survey pages
If that's the case, we just need a way to force `tz` to update every time the survey is launched

**Comment by JGreenlee** [comment]
If my guess is right, then 1c74c6a should have fixed it @sebastianbarry

**Pull request merged**
